name: BIST Sinyal Botu

on:
  schedule:
    - cron: '*/5 * * * *' # Artık her 5 dakikada bir çalışacak
  workflow_dispatch: # İstediğin zaman manuel çalıştırabilmen için tuş

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Kopyala
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install yfinance pandas requests

      - name: Botu Çalıştır
        run: |
          python bot.py
